name: autofix.ci

on:
  push:
    branches:
      - main
      - 'progressive-web-app-design'

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: autofix.ci
        uses: autofix-ci/action@v1.3.2
        with:
          fail-fast: true
          commit-message: "chore: autofix code issues"
